  # set default facts
- name: "Set default facts"
  set_fact:
    _flush_resolve_argument:
    _flush_noproxy_argument:
    _flush_insecure_argument:

  # use custom filter plugin to parse the target
- name: "{{ item }} : parse"
  set_fact:
    _flush_target : "{{ item | parse_url }}"

  # set curl --resolve parameter when enabled
- name: "{{ item }} : Add '--resolve'"
  set_fact:
    _flush_resolve_argument: '--resolve "{{ _flush_target.hostname }}:{{ _flush_target.scheme_port }}:{{ aem_dispatcher_flush_resolve_ip }}"'
  when: aem_dispatcher_flush_resolve_ip is defined

  #- name: Add --noproxy option when defined
- name: "{{ item }} : Add '--noproxy'"
  set_fact:
    _flush_noproxy_argument: '--noproxy {{ _flush_target.hostname }}'
  when: aem_dispatcher_flush_noproxy

# set curl -k parameter when enabled
- name: "{{ item }} : Add '-k'"
  set_fact:
    _flush_insecure_argument: '-k'
  when: aem_dispatcher_flush_insecure

- name: "{{ item }} : flush"
  shell: 'curl \
    {{ _flush_resolve_argument }} \
    {{ _flush_noproxy_argument }} \
    {{ _flush_insecure_argument }} \
    --max-time {{ aem_dispatcher_flush_timeout }} \
    --connect-timeout {{ aem_dispatcher_flush_connect_timeout }} \
    -X POST \
    -H "CQ-Action: {{ aem_dispatcher_flush_cq_action }}" \
    -H "CQ-Handle: {{ aem_dispatcher_flush_cq_handle }}" \
    --write-out %{http_code} \
    --output /dev/null --silent --head --fail \
    {{ item }}{{ aem_dispatcher_flush_location }}'
  args:
    warn: false
  register: aem_dispatcher_flush_result
  failed_when: aem_dispatcher_flush_result.stdout != "200"